# Generated by Django 2.1 on 2022-09-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='quantity',
        ),
    ]
