# Generated by Django 2.1 on 2022-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='stock',
        ),
    ]
