# Generated by Django 2.1 on 2022-09-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_auto_20220916_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
